### ISSUE TITLE
Change from absolute to relative links.

### ISSUE THREAD

**Issue by sechilds** [cirpa-acpri/codeshare#1]
Currently there are absolute links -- which mean that they are pointing to the original repo. (That's going to be confusing.)

**Comment by Sopwith** [comment]
Pray tell, how does one create relative links?

**Comment by sechilds** [comment]
Instead of the whole URL, you put the difference between the location of the current page and the location.

See 29f9b1087fe2c9795c7054fd3eea70010a6127f7 for an example.

**Comment by Sopwith** [comment]
I believe this has been fixed - for now.
